# Generated by Django 6.0.2 on 2026-03-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='fssai_certificate',
            field=models.ImageField(blank=True, default='', upload_to='fssai_certs/'),
        ),
        migrations.AddField(
            model_name='store',
            name='fssai_number',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
        migrations.AddField(
            model_name='store',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='store',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
